package fr.atlantique.imt.inf211.jobmngt.entity;
// Generated Mar 3, 2025, 4:38:44 PM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.GenerationType;
import jakarta.persistence.SequenceGenerator;
 import jakarta.persistence.GeneratedValue;
 import com.fasterxml.jackson.annotation.JsonIdentityInfo;
 import com.fasterxml.jackson.annotation.ObjectIdGenerators;import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Application generated by hbm2java
 */
@Entity
@Table(name="application"
    ,schema="public"
)
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class,property = "id")
public class Application  implements java.io.Serializable {


     private int id;
     private Candidate candidate;
     private QualificationLevel qualificationlevel;
     private String cv;
     private Date appdate;
     private Set<ApplicationMessage> applicationmessages = new HashSet<ApplicationMessage>(0);
     private Set<OfferMessage> offermessages = new HashSet<OfferMessage>(0);
     private Set<Sector> sectors = new HashSet<Sector>(0);

    public Application() {
    }

	
    public Application(int id, Candidate candidate, QualificationLevel qualificationlevel, String cv) {
        this.id = id;
        this.candidate = candidate;
        this.qualificationlevel = qualificationlevel;
        this.cv = cv;
    }
    public Application(int id, Candidate candidate, QualificationLevel qualificationlevel, String cv, Date appdate, Set<ApplicationMessage> applicationmessages, Set<OfferMessage> offermessages, Set<Sector> sectors) {
       this.id = id;
       this.candidate = candidate;
       this.qualificationlevel = qualificationlevel;
       this.cv = cv;
       this.appdate = appdate;
       this.applicationmessages = applicationmessages;
       this.offermessages = offermessages;
       this.sectors = sectors;
    }
   
     @Id
	@SequenceGenerator(name = "APPLICATION_ID_GENERATOR", sequenceName = "APPLICATION_ID_SEQ",allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "APPLICATION_ID_GENERATOR") 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="candidateid", nullable=false)
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="qualiflevelid", nullable=false)
    public QualificationLevel getQualificationlevel() {
        return this.qualificationlevel;
    }
    
    public void setQualificationlevel(QualificationLevel qualificationlevel) {
        this.qualificationlevel = qualificationlevel;
    }

    
    @Column(name="cv", nullable=false)
    public String getCv() {
        return this.cv;
    }
    
    public void setCv(String cv) {
        this.cv = cv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="appdate", length=13)
    public Date getAppdate() {
        return this.appdate;
    }
    
    public void setAppdate(Date appdate) {
        this.appdate = appdate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="application")
    public Set<ApplicationMessage> getApplicationmessages() {
        return this.applicationmessages;
    }
    
    public void setApplicationmessages(Set<ApplicationMessage> applicationmessages) {
        this.applicationmessages = applicationmessages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="application")
    public Set<OfferMessage> getOffermessages() {
        return this.offermessages;
    }
    
    public void setOffermessages(Set<OfferMessage> offermessages) {
        this.offermessages = offermessages;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="indexapplicationsector", schema="public", joinColumns = { 
        @JoinColumn(name="applicationid", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="sectorid", nullable=false, updatable=false) })
    public Set<Sector> getSectors() {
        return this.sectors;
    }
    
    public void setSectors(Set<Sector> sectors) {
        this.sectors = sectors;
    }
}