package fr.atlantique.imt.inf211.jobmngt.entity;
// Generated Mar 3, 2025, 4:38:44 PM by Hibernate Tools 5.6.15.Final

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Candidate generated by hbm2java
 */
@Entity
@Table(name="candidate"
    ,schema="public"
)
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class,property = "id")
public class Candidate  implements java.io.Serializable {


    private int id;
    private AppUser appuser;
    private String lastname;
    private String firstname;
    private Set<Application> applications = new HashSet<>(0);

    public Candidate() {
    }

	
    public Candidate(AppUser appuser, String lastname, String firstname) {
        this.appuser = appuser;
        this.lastname = lastname;
        this.firstname = firstname;
    }
    public Candidate(AppUser appuser, String lastname, String firstname, Set<Application> applications) {
       this.appuser = appuser;
       this.lastname = lastname;
       this.firstname = firstname;
       this.applications = applications;
    }
   
    @GenericGenerator(name="CandidateIdGenerator", strategy="foreign", parameters=@Parameter(name="property", value="appuser"))@Id
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public AppUser getAppuser() {
        return this.appuser;
    }
    
    public void setAppuser(AppUser appuser) {
        this.appuser = appuser;
    }

    
    @Column(name="lastname", nullable=false, length=50)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="firstname", nullable=false, length=50)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidate")
    public Set<Application> getApplications() {
        return this.applications;
    }
    
    public void setApplications(Set<Application> applications) {
        this.applications = applications;
    }
}