package fr.atlantique.imt.inf211.jobmngt.entity;
// Generated Mar 3, 2025, 4:38:44 PM by Hibernate Tools 5.6.15.Final


import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
 import com.fasterxml.jackson.annotation.ObjectIdGenerators;

 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * OfferMessage generated by hbm2java
 */
@Entity
@Table(name="offermessage"
    ,schema="public"
)
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class,property = "id")
public class OfferMessage  implements java.io.Serializable {


     private int id;
     private Application application;
     private JobOffer joboffer;
     private Date sentdate;
     private String message;

    public OfferMessage() {
    }

	
    public OfferMessage(int id, Application application, JobOffer joboffer, String message) {
        this.id = id;
        this.application = application;
        this.joboffer = joboffer;
        this.message = message;
    }
    public OfferMessage(int id, Application application, JobOffer joboffer, Date sentdate, String message) {
       this.id = id;
       this.application = application;
       this.joboffer = joboffer;
       this.sentdate = sentdate;
       this.message = message;
    }
   
     @Id
	@SequenceGenerator(name = "OFFERMESSAGE_ID_GENERATOR", sequenceName = "OFFERMESSAGE_ID_SEQ",allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "OFFERMESSAGE_ID_GENERATOR") 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="applicationid", nullable=false)
    public Application getApplication() {
        return this.application;
    }
    
    public void setApplication(Application application) {
        this.application = application;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jobofferid", nullable=false)
    public JobOffer getJoboffer() {
        return this.joboffer;
    }
    
    public void setJoboffer(JobOffer joboffer) {
        this.joboffer = joboffer;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="sentdate", length=13)
    public Date getSentdate() {
        return this.sentdate;
    }
    
    public void setSentdate(Date sentdate) {
        this.sentdate = sentdate;
    }

    
    @Column(name="message", nullable=false)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


